version: "3"
services:
  my-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
  mongodb:
    image: mongo
    ports:
      - '27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=server
      - MONGO_INITDB_ROOT_PASSWORD=noPass4tooDay
      - MONGO_INITDB_DATABASE=stats
    volumes:
      - /data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
