services:
  my-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
  mongodb:
    image: mongo
    ports:
      - ${MONGODB_PORT}:27017
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=stats
    volumes:
      - /data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
