import { firstLetterUpperCase } from "~~/shared/utils/text";

export function useExplanations(
	type: string,
	stat: string,
): string | undefined {
	switch (type.toLowerCase()) {
		case "mod":
		case "plugin":
		case "datapack":
		case "shader":
		case "resourcepack":
		case "modpack":
			return getProjectStatsExplanation(stat, type);
		case "projects":
			return `
 <h4>Number of Projects across all ProjectTypes</h4>
 <br/>
 This Count includes all projects types (mods, plugins, datapacks, shaders, resourcepacks, modpacks).
 `;
		case "versions":
			return `
 <h4>Number of Versions across all ProjectTypes</h4>
 <br/>
 This Count includes all projects types (mods, plugins, datapacks, shaders, resourcepacks, modpacks).
 `;
		case "authors":
			return `
 <h4>Number of Authors on Modrinth</h4>
 `;
		case "files":
			return `
 <h4>Number of Files hosted on Modrinth</h4>
 `;
		case "revenue":
			return `
 <h4>Revenue Generated by Modrinth in USD</h4>
 <br/>
 The revenue is Split between Modrinth and the Creators.
 `;
	}
}

function getProjectStatsExplanation(stat: string, type: string) {
	switch (stat.toLowerCase()) {
		case "versions": {
			return `
 <h4>Number of Versions Supporting Each Loader/Game-Version</h4>
 <br/>
 Each version will be counted separately for every loader or game-version it supports. If a version supports multiple loaders or game-versions, it will be counted once for each supported loader/game-version.
 `;
		}
		case "count": {
			return `
 <h4>Number of ${firstLetterUpperCase(type)}s Supporting Each Loader/Game-Version</h4>
 <br/>
 Each ${firstLetterUpperCase(type)} will only be counted once. This means if a ${firstLetterUpperCase(type)} has 10 versions supporting a single game-version in will still only be counted once.
 `;
		}
		case "downloads": {
			return `
 <h4>Number of Downloads per Specific Loader/Game-Version</h4>
 <br/>
 If a version supports multiple loaders or game-versions, the downloads will be divided equally among each supported loader/game-version.
 <br/>
 <br/>
 This may exaggerate widely supported but less commonly used loaders or versions, such as Quilt.
 `;
		}
	}
}
